#!/usr/bin/env node
(function() {
  var complete, fs, omelette;

  fs = require("fs");

  omelette = require("../src/omelette");

  complete = omelette("githubber|ghb|gh|g <action> <user> <repo>");

  complete.on("action", function() {
    this.reply(["star","clone", "update", "push"]);
  });

  complete.on("user", function(action) {
    this.reply(fs.readdirSync("/Users/"));
  });

  complete.on("repo", function(user) {
    this.reply(["http://github.com/" + user + "/helloworld", "http://github.com/" + user + "/blabla"]);
  });

  complete.init();

  // If you want to setup, you can use `omeletteInstance.setupShellInitFile()` function.
  if (~process.argv.indexOf('--setup')) {
    complete.setupShellInitFile();
  }

  console.log("Your program's default workflow.");
  console.log(process.argv);

}).call(this);
