#!/usr/bin/env node
(function() {
  var complete, fs, omelette;

  fs = require("fs");

  omelette = require("../src/omelette");

  complete = omelette("githubber <action> <user> <repo>");

  complete.on("action", function() {
    return this.reply(["star","clone", "update", "push"]);
  });

  complete.on("user", function(action) {
    return this.reply(fs.readdirSync("/Users/"));
  });

  complete.on("repo", function(user) {
    return this.reply(["http://github.com/" + user + "/helloworld", "http://github.com/" + user + "/blabla"]);
  });

  complete.init();

  console.log("Your program's default workflow.");
  console.log(process.argv);

}).call(this);
